# Generated by Django 5.1.5 on 2026-06-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Algorithm config, e.g. {"algorithm": "kmeans", "max_k": 10}')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='topics.topic')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('algorithm', models.CharField(default='kmeans', max_length=20)),
                ('member_count', models.IntegerField(default=0)),
                ('coherence_score', models.FloatField(default=0.0, help_text='Intra-cluster similarity — higher is better')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='analysis.analysisrun')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='topics.topic')),
            ],
            options={
                'ordering': ['-member_count'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend_spike', 'Trend Spike'), ('sentiment_shift', 'Sentiment Shift'), ('cluster_summary', 'Cluster Summary'), ('explanation', 'Explanation')], max_length=30)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=0.0, help_text='0.0 to 1.0 — how confident the system is in this insight')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Supporting data: spike timestamps, keyword lists, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analysis.analysisrun')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='topics.topic')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_score', models.FloatField(help_text='VADER compound: -1.0 to 1.0')),
                ('positive_score', models.FloatField(help_text='Positive component: 0 to 1')),
                ('negative_score', models.FloatField(help_text='Negative component: 0 to 1')),
                ('neutral_score', models.FloatField(help_text='Neutral component: 0 to 1')),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='topics.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance from cluster centroid')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='analysis.cluster')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='topics.discussion')),
            ],
            options={
                'ordering': ['distance'],
                'unique_together': {('discussion', 'cluster')},
            },
        ),
    ]
