# Generated by Django 5.1.5 on 2026-06-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(help_text='Serialized numpy float32 array (384 dimensions = 1,536 bytes)')),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', help_text='Sentence-transformer model used to generate this embedding', max_length=100)),
                ('dimensions', models.IntegerField(default=384, help_text='Vector dimensionality (must match model output)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='topics.discussion')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name'], name='idx_embedding_model')],
            },
        ),
    ]
