# Generated by Django 5.1.5 on 2026-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='sentiment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated sentiment: {"avg_score": -0.42, "label": "negative", "positive_pct": 20, ...}'),
        ),
    ]
