# Generated by Django 5.1.5 on 2026-06-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-provided topic query, e.g. 'AI in education'", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Auto-generated summary after analysis completes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting Data'), ('analyzing', 'Running Analysis'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('youtube', 'YouTube')], max_length=20)),
                ('source_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='topics.topic')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['topic', 'published_at'], name='idx_discussion_timeline')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='unique_source_discussion')],
            },
        ),
    ]
